### ISSUE TITLE
Support for Kibana 6?

### ISSUE THREAD

**Issue by indypinball** [sbeyn/kibana-plugin-traffic-sg#8]
Hi
I'm wondering if there are any plans for supporting version 6 of Kibana in the near future? 
Regards
Tonni

**Comment by snuids** [comment]
@tonnihult 

I have a similar plugin compatible with Kibana 6 [here](https://github.com/snuids/TrafficLightVisKibana6). We all derivated our code from the original logz  one. My version has a few extras features such as multiple lights per line.

Hope it helps,

**Comment by indypinball** [comment]
Thanx @snuids I'll test your plugin
